### ISSUE TITLE
Readme example is not working

### ISSUE THREAD

**Issue by mroavi** [simeonschaub/ArtifactUtils.jl#13]
Hello. I haven't been able to get the first example presented in the README to work. I'm using Julia Version 1.7.2 (2022-02-06).

I created and instantiated a project, added `]add ArtifactUtils`, and ran the following code:

```julia
using ArtifactUtils, Artifacts # Artifacts provides the artifact string macro

add_artifact!(
              "Artifacts.toml",
              "JuliaMono",
              "https://github.com/cormullion/juliamono/releases/download/v0.030/JuliaMono.tar.gz",
              force=true,
             )

import Pkg; Pkg.instantiate() # to install the artifact

artifact"JuliaMono"
```
which outputs the following error (triggered by the last line):

```julia
ERROR: LoadError: Artifact "JuliaMono" was not installed correctly. Try `using Pkg; Pkg.instantiate()` to re-install all missing resources.
```

Running  `using Pkg; Pkg.instantiate()` does not give an error but the artifact is not installed (I verified that 6c460cf2eccecd24499618112adbbe7e403fa1ee is not in ~/.julia/artifacts).

**Comment by simeonschaub** [comment]
Ah, this now needs to call `Pkg.ensure_artifact_installed` instead of `Pkg.instantiate`. I have updated the README accordingly now, could you let me know if that works for you?

**Comment by mroavi** [comment]
It works now! Thanks a lot!
