### ISSUE TITLE
Add a way to modify `download` options

### ISSUE THREAD

**Issue by BambOoxX** [simeonschaub/ArtifactUtils.jl#18]
Currently the download of an artifact does not allow using `download` options.
https://github.com/simeonschaub/ArtifactUtils.jl/blob/810f73541be2cb4bc23ac72caca3193fe78e8a2e/src/ArtifactUtils.jl#L62

It would be nice to have a complete access to the `download` arguments.
In my case, this is because I need to provide a `HEADER` to the request.

**Comment by simeonschaub** [comment]
Seems like a good idea! Want to make a PR?

**Comment by BambOoxX** [comment]
I'll try and propose something today.

**Comment by BambOoxX** [comment]
@simeonschaub I've managed to adapt the code to create the Artifacts with additional `download` options, although this may not be a good option. In my case, I used the `headers` options to provide a `PRIVATE-TOKEN` for authentication, but there does not seem to be a way to apply this strategy for users of the package. FYI I've posted a question about this on the discourse https://discourse.julialang.org/t/downloading-a-file-with-authentification-fails-with-a-netrc-but-not-with-header/96057

**Comment by BambOoxX** [comment]
@simeonschaub I'll close it for now since it does not seem possible to take advantage of additional `download` configuration at package download

**Comment by BambOoxX** [comment]
This one could be reopened once https://github.com/JuliaLang/Pkg.jl/issues/1888 is closed
