### ISSUE TITLE
Artifacts that are not tar archives?

### ISSUE THREAD

**Issue by dpo** [simeonschaub/ArtifactUtils.jl#2]
Many thanks for this life-saving package!

I'm trying to add artifacts that are not tar archives or compressed files (i am not the author of the artifacts, so can't change them). But trying to add such artifacts gives me the error
```
tar: Error opening archive: Unrecognized archive format
```
What's the appropriate syntax?

**Comment by giordano** [comment]
Unfortunately, artifacts can only be tarballs with the following extensions: https://github.com/JuliaLang/Pkg.jl/blob/8cbd11723f27ce2feef229aaf944924ab355d864/src/PlatformEngines.jl#L470

**Comment by simeonschaub** [comment]
Yes, you might want to check out https://github.com/oxinabox/DataDeps.jl for downloading non-tar archives or files instead.
