### ISSUE TITLE
call to probe_platform_engines! will break in Julia 1.8

### ISSUE THREAD

**Issue by StefanKarpinski** [simeonschaub/ArtifactUtils.jl#3]
https://github.com/JuliaLang/Pkg.jl/pull/2641 deletes the internal `probe_platform_engines!` which this package calls. This has been a no-op for since Julia 1.6: you can now just download stuff without calling that. As a result:

* Old versions of this package will break with Julia 1.8, so they will need to be capped in the registry
* To support both Julia ≤ 1.5 and ≥ 1.6 at the same time, check if the function exists before calling it
* To support only Julia ≥ 1.6 you can simply delete the call to `probe_platform_engines!`

**Comment by simeonschaub** [comment]
Thanks for the notice!

> Old versions of this package will break with Julia 1.8, so they will need to be capped in the registry

Is capping older versions even necessary? In the past, I have just tagged new patch releases with the necessary fixes for new Julia versions.

**Comment by StefanKarpinski** [comment]
In theory the resolver could somehow end up giving someone a bad combinations, but it probably won't happen in practice. It would require someone putting a cap on this package as a dependency at a release that calls `probe_platform_engines!` that excludes the newer versions that don't, which is possible but unlikely.
